[package]
name = "songma_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
serde = { version = "^1.0.57", features = ["derive"] }
serde_json = "^1.0.57"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full","extra-traits"] }

